spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher