server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.17.6.189:3306/tf_test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456